// firebase_options.dart
// TODO: Replace this file with the actual firebase_options.dart generated by
// running `flutterfire configure` after setting up your Firebase project at
// https://console.firebase.google.com
//
// Steps to set up Firebase:
// 1. Create a new Firebase project at https://console.firebase.google.com
// 2. Add an Android app with package name: com.jainish.face_detection_app
// 3. Download google-services.json and place in android/app/
// 4. Install FlutterFire CLI: `dart pub global activate flutterfire_cli`
// 5. Run: `flutterfire configure`
// 6. This will auto-generate the real firebase_options.dart

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIm0ThgjtpdzfZYNzeRA_3WIiKaJfiRjk',
    appId: '1:295680754005:android:bf1aff2a8cc9e2c3daafdc',
    messagingSenderId: '295680754005',
    projectId: 'facedetectionapp-f2016',
    storageBucket: 'facedetectionapp-f2016.firebasestorage.app',
  );

  // TODO: Replace with your actual Firebase configuration values
}